sudo: required
language: php
dist: trusty

services: mysql

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS testing;"
  - mysql -e "GRANT ALL ON testing.* to 'homestead'@'%' IDENTIFIED BY 'secret';"
  - mysql -e --database testing < ci/sqlgrey.sql

install:
  - cp -nv ci/.env.testing .env
  - php artisan key:generate
  - php artisan migrate --force
  - mysql -uroot --database testing < sqlgrey.sql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &

script:
  - php artisan dusk
  - ./vendor/bin/phpunit
